language: c
compiler:
  - clang
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - autoconf-archive
      - intltool
      - libgtk-3-dev
      - libsdl2-dev
      - libxtst-dev
      - libxml2-utils

script:
  - ./autogen.sh
  - make -j1
